#pragma checksum "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "668c1390df02d3d1b016da0c65bb2551c189cc8e0b6f350680251082b059b364"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Personal_Search), @"mvc.1.0.view", @"/Views/Personal/Search.cshtml")]
namespace AspNetCore
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\_ViewImports.cshtml"
using PL;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\_ViewImports.cshtml"
using PL.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\_ViewImports.cshtml"
using DAL.Entity;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"668c1390df02d3d1b016da0c65bb2551c189cc8e0b6f350680251082b059b364", @"/Views/Personal/Search.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"0a6e6afb651c388271110a3fd4bf8c20eccf798310a6a55ef50f5d365b860c2e", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Personal_Search : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PersonsViewModel>
    #nullable disable
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString(" rounded-circle shadow-lg border   border-info overflow-hidden my-2 "), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("width", new global::Microsoft.AspNetCore.Html.HtmlString("280"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("height", new global::Microsoft.AspNetCore.Html.HtmlString("280"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("alt", new global::Microsoft.AspNetCore.Html.HtmlString("Chield"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString(" rounded-circle    overflow-hidden my-2 shadow-lg "), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("btn btn-outline-danger "), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Father", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_7 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Detielse", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_8 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Mother", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_9 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Details", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_10 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("btn btn-outline-danger m-2"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_11 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Personal", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_12 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "EditReportedChildren", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 2 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
  
    ViewData["Title"] = "Search";

#line default
#line hidden
#nullable disable
            WriteLiteral(@"



<section class="" background-image height section  py-5 text-center d-flex align-items-center justify-content-center "">
    <div class=""background-image widthDetiles rounded shadow-lg the-continer box "">
        <div class=""row "">
            <div class=""col-md-4 mt-3 ShadowElement "">

");
#nullable restore
#line 14 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                 if (Model.Is_he_missing == true)
                {


#line default
#line hidden
#nullable disable
            WriteLiteral("                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "668c1390df02d3d1b016da0c65bb2551c189cc8e0b6f350680251082b059b3648875", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 468, "~/Files/Chiledrens_Images/", 468, 26, true);
#nullable restore
#line 17 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
AddHtmlAttributeValue("", 494, Model.ImageName, 494, 16, false);

#line default
#line hidden
#nullable disable
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
#nullable restore
#line 18 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                }
                else
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "668c1390df02d3d1b016da0c65bb2551c189cc8e0b6f350680251082b059b36411037", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            BeginAddHtmlAttributeValues(__tagHelperExecutionContext, "src", 2, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            AddHtmlAttributeValue("", 721, "~/Files/Chiledrens_Images/", 721, 26, true);
#nullable restore
#line 21 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
AddHtmlAttributeValue("", 747, Model.ImageName, 747, 16, false);

#line default
#line hidden
#nullable disable
            EndAddHtmlAttributeValues(__tagHelperExecutionContext);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
#nullable restore
#line 22 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"

                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                <h4 class=\"font-weight-bolder \">Name</h4>\r\n");
#nullable restore
#line 25 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                 if (Model.Is_he_missing == true)
                {


#line default
#line hidden
#nullable disable
            WriteLiteral("                    <p class=\"lead font-weight-bold text-danger \">");
#nullable restore
#line 28 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                             Write(Model.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral(" </p>\r\n");
#nullable restore
#line 29 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                }
                else
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <p class=\"lead  \">");
#nullable restore
#line 32 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                 Write(Model.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral(" </p>\r\n");
#nullable restore
#line 33 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"

                }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                <h4 class=\"font-weight-bolder\">National number</h4>\r\n");
#nullable restore
#line 37 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                 if (Model.Is_he_missing == true)
                {


#line default
#line hidden
#nullable disable
            WriteLiteral("                    <p class=\"lead font-weight-bold text-danger \">");
#nullable restore
#line 40 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                             Write(Model.NationalPerson_Id);

#line default
#line hidden
#nullable disable
            WriteLiteral(" </p>\r\n");
#nullable restore
#line 41 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"

                }
                else
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <p class=\"lead\">");
#nullable restore
#line 45 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                               Write(Model.NationalPerson_Id);

#line default
#line hidden
#nullable disable
            WriteLiteral(" </p>\r\n");
#nullable restore
#line 46 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"

                }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                <h4 class=\"font-weight-bolder\">Address</h4>\r\n");
#nullable restore
#line 50 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                 if (Model.Is_he_missing == true)
                {


#line default
#line hidden
#nullable disable
            WriteLiteral("                    <p class=\"lead font-weight-bold text-danger  \">");
#nullable restore
#line 53 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                              Write(Model.Address);

#line default
#line hidden
#nullable disable
            WriteLiteral(" </p>\r\n");
#nullable restore
#line 54 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"

                }
                else
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <p class=\"lead\">");
#nullable restore
#line 58 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                               Write(Model.Address);

#line default
#line hidden
#nullable disable
            WriteLiteral(" </p>\r\n");
#nullable restore
#line 59 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n\r\n            </div>\r\n            <div class=\"col-md-8 mt-3  w-100 \">\r\n                <div class=\"hightNots \">\r\n                    <h2 class=\"font-weight-bolder\"> Nots </h2>\r\n                    <p class=\"lead \">");
#nullable restore
#line 66 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                Write(Model.Nots);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n                </div>\r\n\r\n                <div class=\"row mt-5\">\r\n                    <div class=\"col-md-4 text-left m-5 \">\r\n                        <h3 class=\"font-weight-bolder\">Father</h3>\r\n                        <p>");
#nullable restore
#line 72 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                      Write(Model.Father.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n                        <h3 class=\"font-weight-bolder\">Mother</h3>\r\n                        <p>");
#nullable restore
#line 74 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                      Write(Model.Mother.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n                        <h3 class=\"font-weight-bolder\">HomePhoneNumber </h3>\r\n");
#nullable restore
#line 76 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                         if (Model.Is_he_missing == true)
                        {


#line default
#line hidden
#nullable disable
            WriteLiteral("                            <p class=\"lead font-weight-bold text-danger \"><span>0</span>");
#nullable restore
#line 79 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                                                   Write(Model.HomePhoneNumber);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n");
#nullable restore
#line 80 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"

                        }
                        else
                        {

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <p class=\"lead\"><span>0</span>");
#nullable restore
#line 84 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                     Write(Model.HomePhoneNumber);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n");
#nullable restore
#line 85 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </div>\r\n                    <div class=\"col-md-4 text-left m-5 \">\r\n                        <h3>Gender</h3>\r\n");
#nullable restore
#line 90 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                         if (Model.Gender == true)
                        {

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <p> Is Male  <i class=\"fa-solid fa-child-reaching\"></i></p>\r\n");
#nullable restore
#line 93 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                        }
                        else
                        {

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <p> Is Female  <i class=\"fa-solid fa-child-dress\"></i></p>\r\n");
#nullable restore
#line 97 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"

                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <h3>Date Of Birth</h3>\r\n                        <p>");
#nullable restore
#line 100 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                      Write(Model.DateOfBirth);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n                        <br />\r\n                        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "668c1390df02d3d1b016da0c65bb2551c189cc8e0b6f350680251082b059b36422389", async() => {
                WriteLiteral("Father");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_6.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_6);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_7.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_7);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#nullable restore
#line 102 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                                                                           WriteLiteral(Model.National_Father_Id_FK);

#line default
#line hidden
#nullable disable
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "668c1390df02d3d1b016da0c65bb2551c189cc8e0b6f350680251082b059b36424983", async() => {
                WriteLiteral("Mother");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_8.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_9.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_9);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#nullable restore
#line 103 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                                                                          WriteLiteral(Model.National_Mother_Id_FK);

#line default
#line hidden
#nullable disable
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                        \r\n                        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "668c1390df02d3d1b016da0c65bb2551c189cc8e0b6f350680251082b059b36427604", async() => {
                WriteLiteral("Report Children");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_10);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_11.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_11);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_12.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_12);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#nullable restore
#line 105 "D:\Route Back-End\zz\Project Graduation\project V 17\project V 17\PL\Views\Personal\Search.cshtml"
                                                                                                                            WriteLiteral(Model.NationalPerson_Id);

#line default
#line hidden
#nullable disable
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                    </div>\r\n\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</section>\r\n");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PersonsViewModel> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
